name: cicd

on:
  push:
    branches: [master]
  workflow_dispatch:


jobs:

  code:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Code
        run: echo "code clone from github"

  build:
    runs-on: ubuntu-slim
    steps:
      - name: Build Docker Container
        run: echo "Docker Container Builded"

  test:
    runs-on: ubuntu-slim
    steps:
      - name: Testing Code
        run: echo "Code Tested"

  deploy:
    runs-on: ubuntu-slim
    steps:
      - name: Deploying App
        run: echo "Docker Deployed The APP"
